module.exports = [
  "Whoops! Look like you're never doing work.",
  "Spawning 1000 distractions...",
  "Starting disapointment.exe on parents.exe...",
  "Minimizing the tab because the teacher walked by...",
  "Converting your GPA into internet lag...",
  "Loading excuses for missing homework...",
  "Hiding from responsibilities.exe...",
  "Calculated probability of getting grounded: 99%...",
  "Forget the essay, look at this meme.",
  "Alt-Tab reflex training in progress...",
  "Sacrificing your education for a chat room...",
  "Asking ChatGPT how to fix this loading bug...",
  "Waiting for Gvbvdxx to figure out JavaScript...",
  "Bypassing the school firewall (just kidding)...",
  "Connecting via potato wi-fi...",
  "Downloading more RAM...",
  "Running code that barely works...",
  "Blame the lag on your ISP.",
  "Stealing code from Stack Overflow...",
  "No servers were harmed in the making of this load time.",
  "Pre-loading 500 vine boom sound effects...",
  "Calibrating microphone for maximum volume...",
  "Preparing your eardrums for destruction...",
  "Fighting for the screenshare slot...",
  "MOP 3000 is animating the pixels...",
  "Loading cursed images...",
  "Syncing the chaos to your browser...",
  "Preparing to judge your profile picture...",
  "Checking for cringe content...",
];
