var e = {};
e.MAX_BIO_SIZE = 3000; //Unused function, but kept so breaking doesn't happen.
e.MIN_USERNAME_LENGTH = 3; //Minimal characters.
e.MAX_USERNAME_LENGTH = 20; //Maximum characters.
e.MIN_PASSWORD_LENGTH = 4; //Minimal characters.
e.MAX_PASSWORD_LENGTH = 40; //Maximum characters.
e.MAX_MAIL_SIZE = 1500; //Unused function, but kept so breaking doesn't happen.
e.USERNAME_CHAR_SET =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"; //What characters are allowed in usernames, must be url and file name friendly.
e.MAX_MEDIA_SIZE = 10 * 1024 * 1024; // 10 MB max per file
e.MAX_MEDIA_FOLDER_SIZE = 10 * 1024 * 1024 * 1024; // 10 GB total storage
e.MAX_PROFILE_PICTURE_SIZE = 5000; //50KB
e.MAX_DISPLAY_NAME_SIZE = 35; //Minimal characters.
e.MIN_DISPLAY_NAME_SIZE = 2; //Maximum characters.
e.ROOM_CLEANUP_TIMEOUT = 60000 * 2; // 2 minutes
e.MAX_MESSAGE_SIZE = 1200; //1200 characters.
e.MAX_STORED_MESSAGES = 40; //40 messages max stored per room.
e.MAX_SOCKETS_PER_USER = 12; //Maximum of 12 clients per signed in user.
e.MAX_GUEST_SOCKETS = 20; //Maximum of 20 sockets per user.
e.MAX_REQUESTS_PER_MINUTE = 220; //Maximum of 220 requests per minute for user or ip.
e.MAX_REQUESTS_TIMEOUT = 15000; //Time it takes to timeout requests.
e.BCRYPT_SALT_ROUNDS = 10; //bcryptjs salt rounds used for comparing hashed passwords.
e.MAX_USER_SESSIONS = 15; //Max user sessions per user.
e.MAX_SOCKETS_PER_GUEST_IP = 30; //Max user guest connected sockets.
e.DISPLAYNAME_CHAR_SET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~`!@#$%^&*()-_=+{[]}|\\'\";:/?.>,<";
e.MAX_NOTIFICATIONS = 20; //Max real time notifcations per user.
e.MAX_USERLIST_SIZE = 150; //Max usernames in user list.
e.MAX_ROOM_NAME_SIZE = 230; //230 Characters max of room name.
e.MAX_ROOM_DISCRIPTION_SIZE = 450; //450 Characters max of room discription.

module.exports = e;
